@startuml
class AuthController {
    - <<readonly>> _authRepository : IAuthRepository
    + AuthController(authRepository:IAuthRepository)
    + <<async>> Register(request:UserRegistrationDTO) : Task<IActionResult>
}
ControllerBase <|-- AuthController
@enduml
