@startuml
class CharacterService {
    - <<readonly>> _charactersRepository : ICharactersRepository
    - <<readonly>> _mapper : IMapper
    + CharacterService(mapper:IMapper, charactersRepository:ICharactersRepository)
    + <<async>> CreateNew(addCharacterDTO:AddCharacterDTO) : Task<List<Character>>
    + <<async>> GetAll() : Task<List<Character>>
    + <<async>> GetById(id:int) : Task<Character>
    + <<async>> Update(updateCharacterDTO:Character) : Task<List<Character>>
    + Delete(id:int) : Task<List<Character>>
}
ICharacterService <|-- CharacterService
@enduml
